#!/usr/bin/env groovy

pipeline {
    agent any

    stages {
        stage('Call Jenkins Job') {
            steps {
                build job:'AWS/AWS-CF' , parameters:[
                    string(name: 'GitRepoName', value: "quickstart-datastax-oss"),
                    string(name: 'awsregion', value: 'us-east-1'),
                    booleanParam(name: 'RunNoSqlBench', value: true),
                    booleanParam(name: 'RunCql', value: true),
                    booleanParam(name: 'DeleteStack', value: true)
                ]
            }
        }
    }
}
