AWSTemplateFormatVersion: 2010-09-09
Description: Create Seednodes.
Parameters:
  ClusterName:
    Description: The name of the DDAC Cluster.
    Type: String
    Default: DDAC-Cluster
  CreateClusterWithPublicIP:
    Description: "Whether to create the DDAC Cluster nodes in public subnet"
    Type: String
    Default: "false"
    AllowedValues:
      - "false"
      - "true"
  DatacenterName:
    Description: The name of the DDAC Datacenter.
    Type: String
    Default: DDAC-dc0
  Subnet1ID:
    Description: Private Subnet Id 1 for Seednode1
    Type: 'AWS::EC2::Subnet::Id'
  Subnet2ID:
    Description: Private Subnet Id 2 for Seednode2
    Type: 'AWS::EC2::Subnet::Id'
  KeyPairName:
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: Name of an existing EC2 KeyPair.
  QSS3BucketName:
    AllowedPattern: '^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription: >-
      Quick Start bucket name can include numbers, lowercase letters, uppercase
      letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Default: aws-quickstart
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: '^[0-9a-zA-Z-/]*$'
    ConstraintDescription: >-
      Quick Start key prefix can include numbers, lowercase letters, uppercase
      letters, hyphens (-), and forward slash (/).
    Default: quickstart-datastax-ddac/
    Description: >-
      S3 key prefix for the Quick Start assets. Quick Start key prefix can
      include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  DDACSecGroup:
    Description: "DDAC Security Group ID."
    Type: String
  InstanceType:
    AllowedValues:
      - t2.medium
      - t2.large
      - m4.large
      - m4.xlarge
      - m4.2xlarge
      - m4.4xlarge
      - m4.10xlarge
      - m4.16xlarge
      - c4.large
      - c4.xlarge
      - c4.2xlarge
      - c4.4xlarge
      - c4.8xlarge
      - r4.large
      - r4.xlarge
      - r4.2xlarge
      - r4.4xlarge
      - r4.8xlarge
      - r4.16xlarge
    ConstraintDescription: "Must be a valid EC2 instance type."
    Default: t2.medium
    Description: "EC2 instance type"
    Type: String
  VolumeSize:
    Type: Number
    Description: "EBS volume size of the DDAC Cluster Nodes in GB"
    Default: 1024
  DDACInstallType:
    AllowedValues:
      - Dev
      - Standard
    ConstraintDescription: "Choose Dev / Standard."
    Default: Dev
    Description: "type of install"
    Type: String
  DDACDevInstallNodeCount:
    AllowedValues:
      - 1
      - 2
    ConstraintDescription: "Choose 1 / 2."
    Default: 1
    Description: "Number of nodes for Dev Install"
    Type: Number
Conditions:
  GovCloudCondition: !Equals
    - !Ref AWS::Region
    - us-gov-west-1
  CreateInPublicSubnet: !Equals
    - !Ref CreateClusterWithPublicIP
    - true
  Create2ndNode:
    !Or [!Equals [!Ref DDACDevInstallNodeCount, 2], !Equals [!Ref DDACInstallType, Standard]]
Mappings:
  AWSAMIRegionMap:
    AMI:
      US1804HVM: ubuntu/images/hvm-ssd/ubuntu-xenial-18.04-amd64-server-20180814
    ap-northeast-1:
      US1804HVM: ami-0f6b4f4104d26f399
    ap-northeast-2:
      US1804HVM: ami-02b4a5559ce53a570
    ap-south-1:
      US1804HVM: ami-0245841fc4b40e22f
    ap-southeast-1:
      US1804HVM: ami-07febfdfb4080320e
    ap-southeast-2:
      US1804HVM: ami-04a0f7552cff370ba
    ca-central-1:
      US1804HVM: ami-0972a0d3135cf1fc0
    eu-central-1:
      US1804HVM: ami-09356619876445425
    eu-north-1:
      US1804HVM: ami-005bc7d72deb72a3d
    eu-west-1:
      US1804HVM: ami-04c58523038d79132
    eu-west-2:
      US1804HVM: ami-00622b440d92e55c0
    eu-west-3:
      US1804HVM: ami-0b70d1460d5c7a299
    sa-east-1:
      US1804HVM: ami-049f5d88d2d436431
    us-east-1:
      US1804HVM: ami-00a208c7cdba991ea
    us-east-2:
      US1804HVM: ami-059d836af932792c3
    us-west-1:
      US1804HVM: ami-0f42d8c4eb586ccf7
    us-west-2:
      US1804HVM: ami-0a7d051a1c4b54f65
Resources:
  InstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          -
            Effect: 'Allow'
            Principal:
              Service:
                - 'ec2.amazonaws.com'
            Action:
              - 'sts:AssumeRole'
      Path: '/'
  InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: '/'
      Roles:
        - Ref: 'InstanceRole'
  AuthenticatedS3Policy:
    Type: AWS::IAM::Policy
    Properties:
        PolicyName: AuthenticatedS3GetObjects
        Roles:
        - !Ref InstanceRole
        PolicyDocument:
          Statement:
            - Sid: BucketAccess
              Effect: Allow
              Action:
                - 's3:GetObject'
              Resource: !Sub arn:aws:s3:::${QSS3BucketName}/*
  DDACSeedNode1:
    Type: 'AWS::EC2::Instance'
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    Metadata:
      'AWS::CloudFormation::Authentication':
        S3AccessCreds:
          type: S3
          roleName: !Ref InstanceRole
          buckets: !Ref QSS3BucketName
      'AWS::CloudFormation::Init':
        configSets:
          cs_install:
            - install_and_enable_cfn_hup
            - install_ddac
            - post_install
        install_and_enable_cfn_hup:
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Join
                - ''
                - - |
                    [main]
                  - stack=
                  - !Ref 'AWS::StackId'
                  - |+

                  - region=
                  - !Ref 'AWS::Region'
                  - |+

              mode: '000400'
              owner: root
              group: root
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Join
                - ''
                - - |
                    [cfn-auto-reloader-hook]
                  - |
                    triggers=post.update
                  - >
                    path=Resources.DDACSeedNode1.Metadata.AWS::CloudFormation::Init
                  - 'action=/usr/local/bin/cfn-init -v '
                  - '         --stack '
                  - !Ref 'AWS::StackName'
                  - '         --resource DDACSeedNode1 '
                  - '         --configsets cs_install '
                  - '         --region '
                  - !Ref 'AWS::Region'
                  - |+

                  - |
                    runas=root
            /lib/systemd/system/cfn-hup.service:
              content: !Join
                - ''
                - - |
                    [Unit]
                  - |+
                    Description=cfn-hup daemon

                  - |
                    [Service]
                  - |
                    Type=simple
                  - |
                    ExecStart=/usr/local/bin/cfn-hup
                  - |+
                    Restart=always
                  - |
                    [Install]
                  - WantedBy=multi-user.target
          commands:
            01enable_cfn_hup:
              command: systemctl enable cfn-hup.service
            02start_cfn_hup:
              command: systemctl start cfn-hup.service
        install_ddac:
          # sources:
          #   /home/ubuntu: !Sub
          #       - >-
          #         https://${QSS3BucketName}.${S3Region}.amazonaws.com/${QSS3KeyPrefix}scripts/deploy.tar
          #       - QSS3BucketName: !Ref QSS3BucketName
          #         S3Region: !If [ GovCloudCondition, s3-us-gov-west-1, s3 ]
          #         QSS3KeyPrefix: !Ref QSS3KeyPrefix
          commands:
            01_install_ddac:
              command: "ln -s /home/ubuntu /home/ddac"
            03_keygen:
              command: "/home/ddac/keygen.sh"
            04_run_playbooks:
              command: "/home/ddac/playbooks.sh"
            05_install_ddac:
              command: !Sub |
                #!/bin/bash -xe
                private_ip=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4/)
                ansible-playbook -v -u ubuntu -i /home/ddac/ansible-hosts.cfg --private-key /home/ubuntu/.ssh/id_rsa /home/ddac/ddac-install.yml --extra-vars "cluster_name=${ClusterName} dc=${DatacenterName} seeds=$private_ip"
        post_install:
          commands:
            01_post_install_ddac:
              command: "touch /tmp/01_post_install_ddac"
    Properties:
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - DeleteOnTermination: true
          DeviceIndex: "0"
          SubnetId: !Ref Subnet1ID
          GroupSet:
            - !Ref DDACSecGroup
      KeyName: !Ref KeyPairName
      ImageId: !FindInMap
        - AWSAMIRegionMap
        - !Ref 'AWS::Region'
        - US1804HVM
      BlockDeviceMappings:
        - DeviceName: /dev/xvdf
          Ebs:
            VolumeSize: !Ref VolumeSize
            VolumeType: gp2
      Tags:
          - Key: Name
            Value: DDAC_Seednode1
      UserData:
        Fn::Base64: !Sub
        - |
          #!/bin/bash -xe
          #CFN Signaling fuctions (begin)
          function cfn_fail
          {
            cfn-signal -e 1 --stack ${AWS::StackName} --region ${AWS::Region} --resource DDACSeedNode1
            exit 1
          }
          function cfn_success
          {
            cfn-signal -e 0 --stack ${AWS::StackName} --region ${AWS::Region} --resource DDACSeedNode1
            exit 0
          }
          #Load Linux utils
          until git clone https://github.com/aws-quickstart/quickstart-linux-utilities.git ; do echo "Retrying"; done
          cd /quickstart-linux-utilities && source quickstart-cfn-tools.source
          # Constants
          S3URI=https://${QSS3BucketName}.${S3Region}.amazonaws.com/${QSS3KeyPrefix}
          # Prep operating systems
          qs_update-os || qs_err
          qs_bootstrap_pip || qs_err
          qs_aws-cfn-bootstrap || qs_err
          #Run cfn-init configsets
          cfn-init -v --stack ${AWS::StackName} --resource DDACSeedNode1 --configsets cs_install --region ${AWS::Region} || qs_err
          # Signal cfn-init (final check)
          [ $(qs_status) == 0 ] && cfn_success || cfn_fail

        - S3Region: !If [ GovCloudCondition, s3-us-gov-west-1, s3 ]
  DDACSeedNode2:
    Type: 'AWS::EC2::Instance'
    Condition: Create2ndNode
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    Metadata:
      'AWS::CloudFormation::Authentication':
        S3AccessCreds:
          type: S3
          roleName: !Ref InstanceRole
          buckets: !Ref QSS3BucketName
      'AWS::CloudFormation::Init':
        configSets:
          cs_install:
            - install_and_enable_cfn_hup
            - install_ddac
            - post_install
        install_and_enable_cfn_hup:
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Join
                - ''
                - - |
                    [main]
                  - stack=
                  - !Ref 'AWS::StackId'
                  - |+

                  - region=
                  - !Ref 'AWS::Region'
                  - |+

              mode: '000400'
              owner: root
              group: root
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Join
                - ''
                - - |
                    [cfn-auto-reloader-hook]
                  - |
                    triggers=post.update
                  - >
                    path=Resources.DDACSeedNode2.Metadata.AWS::CloudFormation::Init
                  - 'action=/usr/local/bin/cfn-init -v '
                  - '         --stack '
                  - !Ref 'AWS::StackName'
                  - '         --resource DDACSeedNode2 '
                  - '         --configsets cs_install '
                  - '         --region '
                  - !Ref 'AWS::Region'
                  - |+

                  - |
                    runas=root
            /lib/systemd/system/cfn-hup.service:
              content: !Join
                - ''
                - - |
                    [Unit]
                  - |+
                    Description=cfn-hup daemon

                  - |
                    [Service]
                  - |
                    Type=simple
                  - |
                    ExecStart=/usr/local/bin/cfn-hup
                  - |+
                    Restart=always
                  - |
                    [Install]
                  - WantedBy=multi-user.target
          commands:
            01enable_cfn_hup:
              command: systemctl enable cfn-hup.service
            02start_cfn_hup:
              command: systemctl start cfn-hup.service
        install_ddac:
          # sources:
          #   /home/ubuntu: !Sub
          #       - >-
          #         https://${QSS3BucketName}.${S3Region}.amazonaws.com/${QSS3KeyPrefix}scripts/deploy.tar
          #       - QSS3BucketName: !Ref QSS3BucketName
          #         S3Region: !If [ GovCloudCondition, s3-us-gov-west-1, s3 ]
          #         QSS3KeyPrefix: !Ref QSS3KeyPrefix
          commands:
            01_install_ddac:
              command: "ln -s /home/ubuntu /home/ddac"
            03_keygen:
              command: "/home/ddac/keygen.sh"
            04_run_playbooks:
              command: "/home/ddac/playbooks.sh"
            05_install_ddac:
              command: !Sub |
                #!/bin/bash -xe
                ansible-playbook -v -u ubuntu -i /home/ddac/ansible-hosts.cfg --private-key /home/ubuntu/.ssh/id_rsa /home/ddac/ddac-install.yml --extra-vars "cluster_name=${ClusterName} dc=${DatacenterName} seeds=${DDACSeedNode1.PrivateIp}"
        post_install:
          commands:
            01_post_install_ddac:
              command: "touch /tmp/01_post_install_ddac"
    Properties:
      InstanceType: !Ref InstanceType
      IamInstanceProfile: !Ref InstanceProfile
      NetworkInterfaces:
        - DeleteOnTermination: true
          DeviceIndex: "0"
          # SubnetId: !If [CreateInPublicSubnet, !Ref PublicSubnet2ID, !Ref PrivateSubnet2ID]
          SubnetId: !Ref Subnet2ID
          GroupSet:
            - !Ref DDACSecGroup
      KeyName: !Ref KeyPairName
      ImageId: !FindInMap
        - AWSAMIRegionMap
        - !Ref 'AWS::Region'
        - US1804HVM
      BlockDeviceMappings:
        - DeviceName: /dev/xvdf
          Ebs:
            VolumeSize: !Ref VolumeSize
            VolumeType: gp2
      Tags:
          - Key: Name
            Value: DDAC_Seednode2
      UserData:
        Fn::Base64: !Sub
        - |
          #!/bin/bash -xe
          #CFN Signaling fuctions (begin)
          function cfn_fail
          {
            cfn-signal -e 1 --stack ${AWS::StackName} --region ${AWS::Region} --resource DDACSeedNode2
            exit 1
          }
          function cfn_success
          {
            cfn-signal -e 0 --stack ${AWS::StackName} --region ${AWS::Region} --resource DDACSeedNode2
            exit 0
          }
          #Load Linux utils
          until git clone https://github.com/aws-quickstart/quickstart-linux-utilities.git ; do echo "Retrying"; done
          cd /quickstart-linux-utilities && source quickstart-cfn-tools.source
          # Constants
          S3URI=https://${QSS3BucketName}.${S3Region}.amazonaws.com/${QSS3KeyPrefix}
          # Prep operating systems
          qs_update-os || qs_err
          qs_bootstrap_pip || qs_err
          qs_aws-cfn-bootstrap || qs_err
          #Run cfn-init configsets
          cfn-init -v --stack ${AWS::StackName} --resource DDACSeedNode2 --configsets cs_install --region ${AWS::Region} || qs_err
          # Signal cfn-init (final check)
          [ $(qs_status) == 0 ] && cfn_success || cfn_fail

        - S3Region: !If [ GovCloudCondition, s3-us-gov-west-1, s3 ]
Outputs:
  Seed1PrivateIpAddress:
    Value: !GetAtt DDACSeedNode1.PrivateIp
    Description: 1st Seed Private IP
  Seed1PublicIpAddress:
    Value: !If [CreateInPublicSubnet, !GetAtt DDACSeedNode1.PublicIp, ""]
    Description: 1st Seed Public IP
  Seed2PrivateIpAddress:
    Condition: Create2ndNode
    Value: !GetAtt DDACSeedNode2.PrivateIp
    Description: 2nd Seed Private IP
  Seed2PublicIpAddress :
    Condition: Create2ndNode
    Value: !If [CreateInPublicSubnet, !GetAtt DDACSeedNode2.PublicIp, ""]
    Description: 2nd Seed Public IP
