= Apache Cassandra^TM^ 4.0 on AWS
:imagesdir: images
:icons: font
:toc:
:toc2: left
:toc-title: Quick Start Reference Deployment
:toclevels: 4

== Overview
include::overview.adoc[]

=== Costs and Licenses
include::cost.adoc[]

== Architecture
include::architecture.adoc[]

=== Apache Cassandra Data Centers and Nodes
Apache Cassandra data centers are groups of nodes, related and configured within a cluster for replication purposes. The Quick Start creates 1 data center with 1 - 32 nodes.

Apache Cassandra stores data replicas on multiple nodes to ensure reliability and fault tolerance. A replication strategy determines the nodes where replicas are placed. The replication strategy is defined per keyspace, and is set during keyspace creation. This Quick Start places nodes in each AWS Availability Zone.

== Prerequisites

=== Specialized Knowledge

Before you deploy this Quick Start, we recommend that you become familiar with the following AWS services. (If you are new to AWS, see https://docs.aws.amazon.com/gettingstarted/latest/awsgsg-intro/intro.html[_Getting Started with AWS_].)

- https://aws.amazon.com/documentation/vpc/[_Amazon VPC_]
- https://aws.amazon.com/documentation/ec2/[_Amazon EC2_]
- https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/AmazonEBS.html[_Amazon EBS_]

We also recommend that you become familiar with the features and configuration of Apache Cassandra.

- https://cassandra.apache.org/doc/latest/new/index.html[_Apache Cassandra documentation_]

=== Technical Requirements

This Quick Start uses a Linux AMI (Ubuntu 18.04 LTS) for EC2 instances, and creates EBS volumes and an S3 bucket. The account you run this Quick Start in must have authorization to create these resources.

== Deployment Options
This Quick Start provides two deployment options:

- **Deploy Apache Cassandra into a new VPC** (end-to-end deployment). This option builds a new AWS environment consisting of the VPC, subnets, NAT gateways, security groups, and other infrastructure components, and then deploys Apache Cassandra cluster into this new VPC.
- **Deploy Apache Cassandra into an existing VPC**. This option provisions Apache Cassandra cluster in your existing AWS VPC infrastructure.

The Quick Start provides separate templates for these options. It also lets you configure CIDR blocks, instance types, and Apache Cassandra settings, as discussed later in this guide.

== Deployment Steps

=== Step 1. Prepare An AWS Account

include::prepare_an_aws_account.adoc[]

If necessary, https://console.aws.amazon.com/support/home#/case/create?issueType=service-limit-increase&amp;limitType=service-code-[_request a service limit increase_] for the Amazon EC2 **m4.large** instance type. You might need to do this if you already have an existing deployment that uses this instance type, and you think you might exceed the http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-resource-limits.html[_default limit_] with this reference deployment.

=== Step 2. Launch the stack
[NOTE]
You are responsible for the cost of the AWS services used while running this Quick Start reference deployment. There is no additional cost for using this Quick Start. For full details, see the pricing pages for each AWS service you will be using in this Quick Start. Prices are subject to change.

Choose one of the following options to launch the AWS CloudFormation template into your AWS
account. For help choosing an option, see deployment options earlier in this guide.

[cols=",",options="header",]
|===
| Option 1 - Deploy Apache Cassandra into a new VPC on AWS | Option 2 - Deploy Apache Cassandra into an existing VPC on AWS
|        https://fwd.aws/mR5pP[_Launch_]       |           https://fwd.aws/eq4AJ[_Launch_]
|===

[IMPORTANT]
If you&#39;re deploying Apache Cassandra into an existing VPC, make sure that your VPC has three private subnets in different Availability Zones for the node instances. These subnets require https://docs.aws.amazon.com/vpc/latest/userguide/vpc-nat-gateway.html[_NAT gateways_] or https://docs.aws.amazon.com/vpc/latest/userguide/VPC_NAT_Instance.html[_NAT instances_] in their route tables, to allow the instances to download packages and software without exposing them to the Internet. You&#39;ll also need the domain name option configured in the DHCP options, as explained in the http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_DHCP_Options.html[_Amazon VPC documentation_]. You&#39;ll be prompted for your VPC settings when you launch the Quick Start.

Each deployment takes about 10-15 minutes to complete, depending on the size of the Apache Cassandra cluster to deploy.

1. Check the region that&#39;s displayed in the upper-right corner of the navigation bar, and change it if necessary. This is where the network infrastructure for Apache Cassandra will be built. The template is launched in the US East (Ohio) Region by default.
2. On the **Select Template** page, keep the default setting for the template URL, and then choose **Next**.
3. On the **Specify Details** page, change the stack name if needed. Review the parameters for the template. Provide values for the parameters that require input. For all other parameters, review the default settings and customize them as necessary. When you finish reviewing and customizing the parameters, choose **Next**

In the following tables, parameters are listed by category and described separately for the two deployment options. Parameters for deploying Apache Cassandra into a new VPC and Parameters for deploying Apache Cassandra into an existing VPC

==== Parameters - Option 1
include::params_new_vpc.adoc[]
==== Parameters - Option 2
include::params_existing_vpc.adoc[]

=== Step 3. Test the Deployment
include::test_deploy.adoc[]

=== Step 4. Back Up Your Data
include::backup.adoc[]

== Troubleshooting
include::troubleshooting.adoc[]

== Additional Resources
include::additional.adoc[]

=== GitHub Repository
*Send Us Feedback* +
{empty} +
You can visit our https://github.com/aws-quickstart/quickstart-datastax-oss[_GitHub repository_] to download the templates and scripts for this Quick Start, to post your comments,
and to share your customizations with others.

[TIP]
See releases in git TIP: See releases in git https://github.com/aws-quickstart/quickstart-datastax-oss/releases

=== Document Revisions

[cols=",,",options="header",]
|===
| Date | Change | In sections
| Jun 2020 | Initial publication | — |
|===

{empty} +
{empty} +
{empty} +
© 2020, Amazon Web Services, Inc. or its affiliates, and DataStax, Inc. All rights reserved.

[underline]**Notices**

This document is provided for informational purposes only. It represents AWS’s current product offerings and practices as of the date of issue of this document, which are subject to change without notice. Customers are responsible for making their own independent assessment of the information in this document and any use of AWS’s products or services, each of which is provided “as is” without warranty of any kind, whether express or implied. This document does not create any warranties, representations, contractual commitments, conditions or assurances from AWS, its affiliates, suppliers or licensors. The responsibilities and liabilities of AWS to its customers are controlled by AWS agreements, and this document is not part of, nor does it modify, any agreement between AWS and its customers.

The software included with this paper is licensed under the Apache License, Version 2.0 (the "License"). You may not use this file except in compliance with the License. A copy of the License is located at [http://aws.amazon.com/apache2.0/](http://aws.amazon.com/apache2.0/) or in the "license" file accompanying this file. This code is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.
